name:                amy3
version:             0.1.0.0
github:              "meowcolm024/amy3"
license:             BSD3
author:              "Malcolm Law"
maintainer:          "luoyicong1026@live.com"
copyright:           "2021 Malcolm Law"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/meowcolm024/amy3#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 4
- containers >= 0.6.5 && < 0.7
- transformers >= 0.5.6 && < 0.6
- mtl >= 2.2 && < 3
- optparse-applicative >= 0.16.1 && < 0.17
- text >= 1.2.4 && < 1.3
- interpolatedstring-perl6 >= 1.0 && < 1.1

library:
  source-dirs: src

executables:
  amy3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amy3

tests:
  amy3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amy3
    - hspec
    - process 
